# Generated by Django 2.2 on 2019-06-17 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20190617_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='name',
            new_name='n_type',
        ),
    ]
