# Generated by Django 2.2 on 2019-06-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20190617_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_id',
            field=models.PositiveIntegerField(default=0, verbose_name='ID пользователя'),
        ),
    ]
