# Generated by Django 2.2 on 2019-06-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_notifications_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='sender',
            field=models.URLField(default='', verbose_name='Ссылка на отправителя (пользователь, категория, тег и т.д.)'),
        ),
    ]
