# Generated by Django 2.2 on 2019-06-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_notifications_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания уведомления'),
        ),
    ]
