# Generated by Django 2.2.2 on 2019-06-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20190619_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='n_type',
            field=models.CharField(default='', max_length=40, verbose_name='Название'),
        ),
    ]
