# Generated by Django 2.2.2 on 2019-06-27 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(blank=True, related_name='dialogs', to=settings.AUTH_USER_MODEL, verbose_name='Диалог')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='', max_length=50, verbose_name='Отправитель')),
                ('receiver', models.CharField(default='', max_length=50, verbose_name='Получатель')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата отправления')),
                ('dialog', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='private_messages.Dialog', verbose_name='Диалог')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
