# Generated by Django 2.2.2 on 2019-06-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.CharField(default='', max_length=50, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(default='', max_length=50, verbose_name='Отправитель'),
        ),
    ]
